# Generated by Django 4.2.6 on 2024-01-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="restriction_on_use_count",
            field=models.PositiveIntegerField(default=2),
        ),
    ]
