# Generated by Django 4.2.6 on 2023-10-21 17:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(unique=True, verbose_name='Индекс дня недели(0 - 6)')),
                ('name', models.CharField(max_length=32, verbose_name='Название дня недели')),
                ('worktime_start', models.TimeField(default=datetime.time(6, 0), verbose_name='Начало работы стирки')),
                ('worktime_end', models.TimeField(default=datetime.time(23, 0), verbose_name='Окончание работы стирки')),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Дни',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wash_duration', models.PositiveIntegerField(default=1, verbose_name='Время стирки(одной) в часах')),
                ('available_days', models.ManyToManyField(to='schedule.day', verbose_name='Дни недели для стирки')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Дата дня для стирки')),
                ('time_start', models.TimeField(verbose_name='Начало стирки')),
                ('time_end', models.TimeField(verbose_name='Окончание стирки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, занявший время')),
            ],
            options={
                'verbose_name': 'Ячейка',
                'verbose_name_plural': 'Ячейки',
            },
        ),
    ]
