# Generated by Django 4.2.6 on 2023-11-12 05:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# schedule.migrations.0002_add_days

def create_days(apps, scheme_editor) -> None:
    Day = apps.get_model('schedule', 'Day')
    days = (
        (0, 'Понедельник'),
        (1, 'Вторник'),
        (2, 'Среда'),
        (3, 'Четверг'),
        (4, 'Пятница'),
        (5, 'Суббота'),
        (6, 'Воскресенье'),
    )

    for day in days:
        Day.objects.create(
            index=day[0],
            name=day[1],
        )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(unique=True, verbose_name='Индекс дня недели(0 - 6)')),
                ('name', models.CharField(max_length=32, verbose_name='Название дня недели')),
                ('worktime_start', models.TimeField(default=datetime.time(6, 0), verbose_name='Начало работы стирки')),
                (
                'worktime_end', models.TimeField(default=datetime.time(23, 0), verbose_name='Окончание работы стирки')),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Дни',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wash_duration', models.PositiveIntegerField(default=1, verbose_name='Время стирки(одной) в часах')),
                ('available_days', models.ManyToManyField(to='schedule.day', verbose_name='Дни недели для стирки')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.RunPython(
            code=create_days,
        ),
        migrations.CreateModel(
            name='Talon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date',
                 models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата дня для стирки')),
                ('time_start', models.TimeField(verbose_name='Начало стирки')),
                ('time_end', models.TimeField(verbose_name='Окончание стирки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                           verbose_name='Пользователь, занявший время')),
                ('week_id', models.IntegerField(blank=True, default=0)),
                ('day_id', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Талон',
                'verbose_name_plural': 'Талоны',
            },
        ),
    ]
