# Generated by Django 4.2.6 on 2023-10-21 17:29

from django.db import migrations


def create_days(apps, scheme_editor) -> None:
    Day = apps.get_model('schedule', 'Day')
    days = (
        (0, 'Понедельник'),
        (1, 'Вторник'),
        (2, 'Среда'),
        (3, 'Четверг'),
        (4, 'Пятница'),
        (5, 'Суббота'),
        (6, 'Воскресенье'),
    )

    for day in days:
        Day.objects.create(
            index=day[0],
            name=day[1],
        )


class Migration(migrations.Migration):
    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_days)
    ]
