# Generated by Django 4.2.6 on 2024-01-05 09:52
import datetime

from django.db import migrations


def create_days(apps, schema_editor):
    Day = apps.get_model('schedule', 'Day')

    for index in range(7):
        Day.objects.create(
            index=index,
            start_time=datetime.time(hour=0, minute=0),
            end_time=datetime.time(hour=0, minute=0),
        )


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_days),
    ]
