# Generated by Django 4.2.6 on 2023-11-12 05:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0003_remove_cell_user_talon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата дня для стирки')),
                ('time_start', models.TimeField(verbose_name='Начало стирки')),
                ('time_end', models.TimeField(verbose_name='Окончание стирки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, занявший время')),
                ('week_id', models.IntegerField(blank=True, default=0)),
                ('day_id', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Талон',
                'verbose_name_plural': 'Талоны',
            },
        ),
        migrations.AddField(
            model_name='cell',
            name='day_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cell',
            name='week_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cell',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.RenameField(
            model_name='cell',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='cell',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата дня для стирки'),
        ),
        migrations.DeleteModel(
            name='Cell',
        ),
    ]
